services:
  upixel-fileserver-prod:
    container_name: upixel-fileserver-prod
    image: upixel-fileserver:prod
    restart: unless-stopped
    environment:
      - UPIXEL_FILESERVER_KEY=${UPIXEL_FILESERVER_KEY}
    ports:
      - 1220:1220
    volumes:
      - /home/schincariol-artur/upixel-fileserver-content:/var/lib/upixel-fileserver
    deploy:
      update_config:
        order: start-first
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
