services:
  upixel_fileserver_staging:
    container_name: upixel_fileserver_staging
    image: ghcr.io/artursrossi/upixel-fileserver:latest
    restart: unless-stopped
    ports:
      - 1231:1220
    volumes:
      - /home/upixel/staging/staging_fileserver_content:/var/lib/upixel-fileserver
    environment:
      - UPIXEL_FILESERVER_KEY=${UPIXEL_FILESERVER_KEY}
    deploy:
      update_config:
        order: start-first
      resources:
        limits:
          cpus: "0.125"
          memory: "128M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:1220/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
