name: uPixel fileserver CI/CD - dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.UPIXEL_GITHUB_TOKEN_PACKAGES }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/artursrossi/upixel-fileserver:latest
            ghcr.io/artursrossi/upixel-fileserver:${{ github.sha }}
